import Link from "next/link"
import "./globals.css"
import { Inter } from "next/font/google"
import LoginBtn from "./LoginBtn"
import { getServerSession } from "next-auth"
import {  authOptions } from "@/pages/api/auth/[...nextauth]"
import LogoutBtn from "./LogoutBtn"
import register from "./register/page"
import Head from "next/head"
const inter = Inter({ subsets: ["latin"] })



export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
  let session =await getServerSession(authOptions)
  console.log(session)
   return (
      <html lang='en'>
       <Head>
 <title>쇼핑몰</title>
 <meta name="description" content="next js로 쇼핑몰 만들기" />
 <meta name="keyword" content="로그인 만들기, 회원가입 만들기, db생성하기" />
       </Head>
         <body className={inter.className}>
            <div className='top-logo'>
               <Link href='/'>
                  <img src='/img/logo.jpg' alt='logo' />
               </Link>
            </div>
            <div className="g-menu">
              <ul>
                <li><Link href="/">HOME</Link></li>
                <li>{session ? <LogoutBtn></LogoutBtn> : <LoginBtn></LoginBtn>}</li>
                <li><Link href="/register">JOIN</Link></li>
 
                <li><Link href="/cart">CART</Link></li>
                <li><Link href="/notice">NOTICE</Link></li>
              </ul>
            </div>
            <nav className="menu">
              <ul>
                <li><Link href="/best100">BEST 100</Link></li>
                <li><Link href="/new">NEW</Link></li>
                <li><Link href="/dress">DRESS</Link></li>
                <li><Link href="/top">TOP</Link></li>
                <li><Link href="/bottom">BOTTOM</Link></li>
                <li><Link href="/outer">OUTER</Link></li>
                <li><Link href="/acc">ACC</Link></li>
                <li><Link href="/sale">SALE</Link></li>
              </ul>
            </nav>
            {children}
            <footer>
              <div className="footer-inner">
                <ul>
                  <li>
                    <h4>NOTIFICATION  </h4>
                      <ul>
                        <li><Link href="/">회사소개</Link></li>
                        <li><Link href="/">이용약관</Link></li>
                        <li><Link href="/">이용안내</Link></li>
                        <li><Link href="/">개인정보취급방침</Link></li>
                        <li><Link href="/">협찬/제휴문의</Link></li>
                      </ul>
                  
                  </li>
                  <li>
                    <h4>COMPANY INFOMATION  </h4>
                      <ul>
                        <li><Link href="/">Company.(주)dk엔터테이먼트</Link></li>
                        <li><Link href="/">Adrdss.서울 서초구 스타프라자 9층</Link></li>
                        <li><Link href="/">Owner.윤채욱</Link></li>
                        <li><Link href="/">Busiess License. 2041-536-544</Link></li>
                        <li><Link href="/">Copyright &copy1 cho line. All Right Resrved.</Link></li>
                      </ul>
                  
                  </li>
                  <li>
                    <h4>BANK ACCOUNT </h4>
                      <ul>
                        <li><Link href="/">국민 135 4668 1157 58</Link></li>
                        <li><Link href="/">농협 352 135 7867 5154</Link></li>
                        <li><Link href="/">신한 135 4525 775 485</Link></li>
                        <li><Link href="/">우리 13574 7528 35454</Link></li>
                        <li><Link href="/">기업 126 123 256 01 014</Link></li>
                      </ul>
                   
                  </li>
                  <li>
                    <h4>CS CENTER</h4>
                      <ul>
                        <li><Link href="/">Weekdat AM 10:00-PM 4:00</Link></li>
                        <li><Link href="/">Lunch AM 10:00-PM 4:00</Link></li>
                        <li><Link href="/">SAT/SUN/HOLIDAY.OFF</Link></li>
                        <li><Link href="/"><span>전화량이 많아 게시판을 이용해 주시면 <br/> 빠르게 답변을 들으실 수 있습니다. </span></Link></li>
                        
                      
                      </ul>
                    <p>02-4532-1000</p>
                  </li>
                </ul>
              </div>

            </footer>
         </body>
      </html>
   )
}
